---
# handlers file for tomcat
  - name: restart tomcat
    service: 
      name: tomcat
      state: restarted

  - name: restart tomcat9
    service:
      name: tomcat9
      state: restarted



  

