---
# tasks file for java
  - name: installing java
    yum:   
      name: java-1.8.0-openjdk
      state: latest
    when: ansible_distribution == "Amazon"
 
  - name: installing java
    apt: 
      name: openjdk-8-jdk
      state: latest
    when: ansible_os_family == "Debian"



